### ISSUE TITLE
Incorrect connect string

### ISSUE THREAD

**Issue by midicase** [NimbeLink/skywire-ppp-scripts#1]
att-S7588-T
connect "/usr/sbin/chat -v -f /etc/ppp/peers/vzw-S7588-T-chat"

probably should be 

connect "/usr/sbin/chat -v -f /etc/ppp/peers/att-S7588-T-chat"

**Comment by kyle-rodgers-nimbelink** [comment]
It has been fixed. Thanks for pointing that out!
