### ISSUE TITLE
How to enable status LED 

### ISSUE THREAD

**Issue by rquackenbush** [NimbeLink/skywire-ppp-scripts#3]
I am using the vzw-GELS/vzw-GELS3-chat files to connect PPP. I would like to enable the status LED as described in section 3.4 of:

http://nimbelink.com/Documentation/Skywire/4G_LTE_Cat_1/30122_NL-SW-LTE-GELS3_Datasheet.pdf

I have attempted to add these commands to the chat file, but it doesn't appear to work (a PPP connection is no longer established in pon returns 8):

```
'' ATZ
SAY 'Configuring LED\n'
OK 'AT^SCFG="GPIO/mode/SYNC","std"'
OK 'AT^SLED=1'
SAY 'Setting APN\n'
OK 'AT+CGDCONT=3,"IPV4V6","[apn]"'
SAY 'Dialing...'
OK 'ATD*99***3#'
CONNECT ''
```

plog is showing the following:

```
Sep  6 08:02:58 raspberrypi chat[10932]: AT+CREG?^M^M
Sep  6 08:02:58 raspberrypi chat[10932]: ERROR^M
Sep  6 08:03:08 raspberrypi chat[10932]: AT+CGREG?^M^M
Sep  6 08:03:08 raspberrypi chat[10932]: ERROR^M
```

Is it appropriate to do this here, or should I do this somewhere else?

**Comment by kyle-rodgers-nimbelink** [comment]
Hello rquackenbush,

For this issue, please submit a ticket to our support system by emailing:

product.support@nimbelink.com

Please also provide your PPP scripts, and your debug logs.

Thank you!

Kyle

**Comment by rquackenbush** [comment]
Done - thanks
